interface ExportableMessage {
  role: "user" | "assistant";
  content: string;
  citations?: { document_title: string; page: number | null; trust_score: number }[];
  confidence?: number | null;
}

export function conversationToMarkdown(
  messages: ExportableMessage[],
  meta: { collegeName?: string | null; exportedBy?: string | null; sessionTitle?: string }
): string {
  const lines: string[] = [];
  lines.push(`# ${meta.sessionTitle || "CampusMind AI conversation"}`);
  lines.push("");
  lines.push(`Exported ${new Date().toLocaleString()}`);
  if (meta.collegeName) lines.push(`College: ${meta.collegeName}`);
  if (meta.exportedBy) lines.push(`Student: ${meta.exportedBy}`);
  lines.push("");
  lines.push("---");
  lines.push("");

  for (const m of messages) {
    if (m.role === "user") {
      lines.push(`**You:** ${m.content}`);
    } else {
      lines.push(`**CampusMind AI:** ${m.content}`);
      if (typeof m.confidence === "number") {
        lines.push("");
        lines.push(`*Confidence: ${Math.round(m.confidence)}%*`);
      }
      if (m.citations && m.citations.length > 0) {
        lines.push("");
        lines.push("Sources:");
        for (const c of m.citations) {
          const page = c.page ? `, page ${c.page}` : "";
          lines.push(`- ${c.document_title}${page} (trust ${Math.round(c.trust_score)}%)`);
        }
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("_Generated by CampusMind AI. Always verify time-sensitive information against official college channels._");

  return lines.join("\n");
}

export function downloadMarkdown(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
